### ISSUE TITLE
VectorDatabase Test Failure: Search_WhenSearchMethodThrowsAnException_ExceptionIsLogged

### ISSUE THREAD

**Issue by nickna** [nickna/Neighborly#67]
```
 Search_WhenSearchMethodThrowsAnException_ExceptionIsLogged
   Source: VectorDatabaseTests.cs line 359
   Duration: 207 ms

  Message: 
  An error should be logged.
Assert.That(logger.LastLogLevel, Is.EqualTo(LogLevel.Error))
  Expected: Error
  But was:  null


  Stack Trace: 
VectorDatabaseTests.Search_WhenSearchMethodThrowsAnException_ExceptionIsLogged() line 371
1)    at VectorDatabaseTests.Search_WhenSearchMethodThrowsAnException_ExceptionIsLogged() in C:\Code\Neighborly\Tests\VectorDatabaseTests.cs:line 371

  Standard Output: 
[15:38:32 INF] Creating temporary file: C:\Users\nbn\AppData\Local\Temp\tmpczcwev.tmp, size 0.05468749997453415 TiB
[15:38:32 INF] Creating temporary file: C:\Users\nbn\AppData\Local\Temp\tmp1fe20z.tmp, size 7.99999999627471 TiB
[15:38:32 ERR] Could not find vector `Neighborly.Vector` in the database searching the -1 nearest neighbor(s).
System.ArgumentOutOfRangeException: Number of neighbors must be greater than 0 (Parameter 'k')
   at Neighborly.Search.SearchService.Search(Vector query, Int32 k, SearchAlgorithm method) in C:\Code\Neighborly\Neighborly\Search\SearchService.cs:line 75
   at Neighborly.VectorDatabase.Search(Vector query, Int32 k, SearchAlgorithm searchMethod) in C:\Code\Neighborly\Neighborly\VectorDatabase.cs:line 79
[15:38:32 INF] Deleted temporary file: C:\Users\nbn\AppData\Local\Temp\tmp1fe20z.tmp
[15:38:32 INF] Deleted temporary file: C:\Users\nbn\AppData\Local\Temp\tmpczcwev.tmp


```

**Comment by nickna** [comment]
Fixed in master. Added a `MockLogger `instance (`_logger`) and then used that in this `Search_WhenSearchMethodThrowsAnException_ExceptionIsLogged.`
